clear all;
clc;
% Analysing field along a single wire...
% Constants 
Magentization = 1.45;
I = -2.5;       %Current flowing in the wire
g = 200e-6;     %Coil spacing
m0 = 4*pi*1e-7;
c = -1000e-6:200e-6:1000e-6;
[X,Y,Z] = meshgrid(c);
radius = 0.5e-3;%m
height = 0.5e-3;%m
vol_cy = pi*radius^2*height; %If Object is Cylinder, vol in m^3
vol_sp = (4/3)*(pi * radius^3); %If Object is Sphere, vol in m^3
density = 7300; %kg/m^3 or 7.3 gm/cc for NdFeB 
mass_cy = density * vol_cy; %kg
mass_sp = density * vol_sp; %kg
gravity = 9.8 ; %m/s^2
Coeff_of_Fric = 1;
Force_cy = Coeff_of_Fric * mass_cy * gravity; %N
Force_sp = Coeff_of_Fric * mass_sp * gravity; %N



% Line along X - axis
% --------------------------------------------------------------Coil_1
x1_1 = -g;
x2_1 = g;
a_yp_1 = g;          %Distance of coil from (0,0)
coil_length_x_1 = x2_1 - x1_1;
k_p_1 = 1/(4*pi*((a_yp_1-Y).^2+Z.^2));
k_1xp_1 = (x2_1-X)./((x2_1-X).^2+(a_yp_1-Y).^2+Z.^2).^0.5;
k_2xp_1 = (x1_1-X)./((x1_1-X).^2+(a_yp_1-Y).^2+Z.^2).^0.5;

Bx_xp_1 = m0*zeros(size(X,1),size(Y,1),size(Z,1));
By_xp_1 = (-Z.*k_p_1.*(k_1xp_1 - k_2xp_1))*I*m0;
Bz_xp_1 = (-(a_yp_1-Y).*k_p_1.*(k_1xp_1 - k_2xp_1))*I*m0;

a_yn_1 = -g;
k_n_1 = 1/(4*pi*((a_yn_1-Y).^2+Z.^2));
k_1xn_1 = (x2_1-X)./((x2_1-X).^2+(a_yn_1-Y).^2+Z.^2).^0.5;
k_2xn_1 = (x1_1-X)./((x1_1-X).^2+(a_yn_1-Y).^2+Z.^2).^0.5;

Bx_xn_1 = m0*zeros(size(X,1),size(Y,1),size(Z,1));
By_xn_1 = (Z.*k_n_1.*(k_1xn_1 - k_2xn_1))*I*m0;
Bz_xn_1 = ((a_yn_1-Y).*k_n_1.*(k_1xn_1 - k_2xn_1))*I*m0;

% --------------------------------------------------------------
% Line along Y - axis
y1_1 = -g;
y2_1 = g;
a_xp_1 = g;          %Distance of coil from (0,0)
coil_length_y_1 = y2_1 - y1_1;

k_yp_1 = 1/(4*pi*((a_xp_1-X).^2+Z.^2));
k_1yp_1 = (y2_1-Y)./((y2_1-Y).^2+(a_xp_1-X).^2+Z.^2).^0.5;
k_2yp_1 = (y1_1-Y)./((y1_1-Y).^2+(a_xp_1-X).^2+Z.^2).^0.5;

Bx_yp_1 = -(Z.*k_yp_1.*(k_1yp_1 - k_2yp_1))*I*m0;
By_yp_1 = m0*zeros(size(X,1),size(Y,1),size(Z,1));
Bz_yp_1 = (-(a_xp_1-X).*k_yp_1.*(k_1yp_1 - k_2yp_1))*I*m0;

a_xn_1 = -g;
k_yn_1 = 1/(4*pi*((a_xn_1-X).^2+Z.^2));
k_1yn_1 = (y2_1-Y)./((y2_1-Y).^2+(a_xn_1-X).^2+Z.^2).^0.5;
k_2yn_1 = (y1_1-Y)./((y1_1-Y).^2+(a_xn_1-X).^2+Z.^2).^0.5;

Bx_yn_1 = (Z.*k_yn_1.*(k_1yn_1 - k_2yn_1))*I*m0;
By_yn_1 = m0*zeros(size(X,1),size(Y,1),size(Z,1));
Bz_yn_1 = ((a_xn_1-X).*k_yn_1.*(k_1yn_1 - k_2yn_1))*I*m0;


% Adding field of the coil
Bx_1 = Bx_xp_1 + Bx_xn_1 + Bx_yp_1 + Bx_yn_1;
By_1 = By_xp_1 + By_xn_1 + By_yp_1 + By_yn_1;
Bz_1 = Bz_xp_1 + Bz_xn_1 + Bz_yp_1 + Bz_yn_1;


[dBx_1_dx,dBx_1_dy,dBx_1_dz] = gradient(Bx_1);
[dBy_1_dx,dBy_1_dy,dBy_1_dz] = gradient(By_1);
[dBz_1_dx,dBz_1_dy,dBz_1_dz] = gradient(Bz_1);

% ----------------------------Force along X - axis----------------------------%
F_x = vol_cy*Magentization*(dBx_1_dx)/m0; %If the magnet Magnetization is in X axis
F_y = vol_cy*Magentization*(dBx_1_dy)/m0; %If the magnet Magnetization is in Y axis
F_z = vol_cy*Magentization*(dBx_1_dz)/m0; %If the magnet Magnetization is in Z axis

% Enter co-ordinates:
p = 5;
q = 5;
r = 4;
height_of_field = Z(:,:,r);
sprintf("Height of Field: %d", height_of_field(:,1))
% sprintf("Force for Magnetization along X axis: %d",F_x(p,q,r))
% sprintf("Force for Magnetization along Y axis: %d",F_y(p,q,r))
sprintf("Force for Magnetization along Z axis & Force required: %d, %d",F_z(p,q,r), Force_cy)
if (F_z(p,q,r) >= Force_cy || F_x(p,q,r) >= Force_cy || F_y(p,q,r) >= Force_cy)
    fprintf("The object moves")
else
    fprintf("The object doesn't move")
end


%
% Plotting graphs
% contourf(X1,Y1,Bz_xp_1(:,:,1))
% d = -800e-6:400e-6:800e-6;
% [X1, Y1, Z1] = meshgrid(d);
% Z(:,1,8)
F_x_s = (squeeze(F_x(:,5,8)))';
F_y_s = (squeeze(F_y(:,5,8)))';
F_z_s = (squeeze(F_z(:,5,8)))';
figure
plot(c,F_x_s, '--b') 
hold on
plot(c,F_y_s, 'g') 
plot(c,F_z_s, 'r') 
line([-1e-3 1e-3],[Force_cy Force_cy],'linewidth',3,'color','r')
legend('F_x','F_y', 'F_z')
xlabel("Distance from Center of wire(m)")
ylabel("Force generated by Field along X - axis (N)")
title("Variation in Force generated by Field along X - axis")
hold off
% streamline(X,Y,Z,dBz_1_dx,dBz_1_dy,dBz_1_dz,X1,Y1,Z1)
% figure
% quiver3(X,Y,Z,F_x,F_y,F_z)
% hold on
% axis([-1e-3 1e-3 -1e-3 1e-3 -1e-3 1e-3])
% line([x1_1 x2_1],[a_yp_1 a_yp_1],'linewidth',3,'color','r');
% line([x1_1 x2_1],[a_yn_1 a_yn_1],'linewidth',3,'color','r');
% line([a_xn_1 a_xn_1],[y1_1 y2_1],'linewidth',3,'color','r');
% line([a_xp_1 a_xp_1],[y1_1 y2_1],'linewidth',3,'color','r');
% G1=plot(0,a_yp_1,'>','markersize',10,"MarkerFaceColor",'g');
% G2=plot(0,a_yn_1,'<','markersize',10,"MarkerFaceColor",'g');
% G3=plot(a_xp_1,0,'<','markersize',10,"MarkerFaceColor",'g');
% G4=plot(a_xn_1,0,'>','markersize',10,"MarkerFaceColor",'g');
% xlabel('X-axis','fontsize',14)
% ylabel('Y-axis','fontsize',14)
% zlabel('Field','fontsize',14)
% title("Force of field along Z-axis")
% hold off
% 
